// src/tests/husband-readiness/config.js - ПРОСТАЯ РАБОЧАЯ ВЕРСИЯ
export default {
  id: 'husband-readiness',
  title: 'Готовность стать мужем Вероники',
  description: 'Узнай, подходишь ли ты мне в мужья! 💕',
  category: 'Личные отношения',
  estimatedTime: '5-7 минут',

  initialQuestions: [
    {
      id: 'positive_traits',
      type: 'multiple',
      question: '💖 Выбери все свои ПОЛОЖИТЕЛЬНЫЕ качества (чем больше, тем лучше!)',
      subtitle: '⭐ - обязательные качества для серьезных отношений',
      options: [
        { value: 'handsome', label: 'Красивый', weight: 20 },
        { value: 'smart', label: 'Умный', weight: 35, required: true },
        { value: 'kind', label: 'Добрый', weight: 15 },
        { value: 'generous', label: 'Щедрый', weight: 15 },
        { value: 'caring', label: 'Заботливый', weight: 20 },
        { value: 'wants_kids', label: 'Хочет со мной детей', weight: 25, required: true },
        {
          value: 'financially_stable',
          label: 'Способен финансово содержать семью',
          weight: 25,
          required: true,
        },
        { value: 'high_income', label: 'Зарабатывает от 10к долларов', weight: 15 },
        { value: 'good_family', label: 'Из хорошей семьи', weight: 5 },
        { value: 'cooks_soup', label: 'Готовит мне любимый супчик', weight: 5, required: true },
        { value: 'loves_travel', label: 'Любит путешествовать', weight: 20 },
        { value: 'healthy_lifestyle', label: 'ЗОЖ', weight: 20 },
        { value: 'secure_attachment', label: 'Надежный тип привязанности', weight: 15 },
        { value: 'faithful', label: 'Верный', weight: 35, required: true },
        { value: 'safe', label: 'С ним безопасно', weight: 15, required: true },
        { value: 'well_dressed', label: 'Хорошо одевается', weight: 5 },
        { value: 'likes_my_outfits', label: 'Любит участвовать в моих нарядах', weight: 5 },
        { value: 'loves_shopping', label: 'Любит шоппинг со мной', weight: 5 },
        { value: 'gives_massage', label: 'Делает мне массаж', weight: 10 },
        { value: 'buys_apartment', label: 'Купить мне квартиру для безопасности', weight: 25 },
        { value: 'gives_gifts', label: 'Дарить мне подарки', weight: 10 },
        { value: 'romantic_courtship', label: 'Красиво ухаживать', weight: 10 },
        { value: 'common_hobbies', label: 'Общие хобби', weight: 10 },
        { value: 'empathetic', label: 'Эмпатичность', weight: 15 },
        { value: 'sense_of_humor', label: 'Чувство юмора', weight: 15 },
      ],
    },
    {
      id: 'negative_traits',
      type: 'multiple',
      question: '🚩 А теперь честно признайся в своих НЕДОСТАТКАХ',
      subtitle: 'За каждый недостаток снимаются баллы. Лучше быть честным!',
      options: [
        { value: 'smoking', label: 'Курящий', weight: -15 },
        { value: 'alcoholic', label: 'Алкозависимый', weight: -40 },
        { value: 'drug_addict', label: 'Наркозависимый', weight: -80 },
        { value: 'adhd', label: 'СДВГ', weight: -15 },
        { value: 'insecure_attachment', label: 'Ненадежный тип привязанности', weight: -15 },
        { value: 'party_lover', label: 'Любит тусоваться', weight: -25 },
        { value: 'angry', label: 'Злой', weight: -20 },
        { value: 'greedy', label: 'Жадный', weight: -20 },
        { value: 'ugly', label: 'Стремно выглядит', weight: -20 },
        { value: 'aggressive', label: 'Агрессивный', weight: -60 },
        { value: 'boring', label: 'Скучный', weight: -40 },
        { value: 'lazy', label: 'Ленивый', weight: -35 },
        { value: 'younger', label: 'Младше меня', weight: -15 },
        { value: 'too_old', label: 'Слишком старше меня', weight: -15 },
        { value: 'childfree', label: 'Чайлдфри', weight: -60 },
      ],
    },
  ],
}
